# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z030sbg485-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/GitHub/VivadoTestProject/testProject/testProject.cache/wt [current_project]
set_property parent.project_path C:/GitHub/VivadoTestProject/testProject/testProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:picozed_7030_fmc2:part0:1.1 [current_project]
set_property ip_output_repo c:/GitHub/VivadoTestProject/testProject/testProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/GitHub/VivadoTestProject/testProject/testProject.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files C:/GitHub/VivadoTestProject/testProject/testProject.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/GitHub/VivadoTestProject/testProject/testProject.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/GitHub/VivadoTestProject/testProject/testProject.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/GitHub/VivadoTestProject/testProject/testProject.srcs/sources_1/bd/system/system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z030sbg485-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
